# generated by Git for Windows (git-bash.exe)


##### Correct PATH variable ( git-bash.exe )

PATH_MINGW=/mingw64/bin:/usr/local/bin:/usr/bin:/bin

PATH_WIN=/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0

PATH_PERL=/usr/bin/vendor_perl:/usr/bin/core_perl


PATH=$PATH_MINGW:$PATH_WIN:$PATH_PERL

#####

# WSL 2
export HOME_L=/l/home/jsoper

export LESSHISTFILE=-

test -f ~/.bashrc  && . ~/.bashrc

# cd to help correct PS1 variable
cd ~

